name: Branches

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches-ignore:
      - main
jobs:
  show-key-values:
    name: show values of variables
    runs-on: ubuntu-latest

    steps:
      - name: run test command
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
  
  call-format-and-lint:
    uses: bpafoshizle/actions/.github/workflows/lint.yml@main

  setup-environment-file:
    name: set up environment file
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          # Write the commands to set the environment variables to a string
          commands="# Set the environment variables
          export POLYGON_TOKEN=\"${{ secrets.POLYGON_TOKEN }}\"
          export TWITCH_BOT_USERNAME=\"${{ secrets.TWITCH_BOT_USERNAME }}\"
          export TWITCH_BOT_CLIENT_ID=\"${{ secrets.TWITCH_BOT_CLIENT_ID }}\"
          export TWITCH_BOT_CLIENT_SECRET=\"${{ secrets.TWITCH_BOT_CLIENT_SECRET }}\"
          export REDDIT_CLIENT_ID=\"${{ secrets.REDDIT_CLIENT_ID }}\"
          export REDDIT_CLIENT_SECRET=\"${{ secrets.REDDIT_CLIENT_SECRET }}\"
          export REDDIT_USERNAME=\"${{ secrets.REDDIT_USERNAME }}\"
          export REDDIT_PASSWORD=\"${{ secrets.REDDIT_PASSWORD }}\"
          export GFYCAT_CLIENT_ID=\"${{ secrets.GFYCAT_CLIENT_ID }}\"
          export GFYCAT_CLIENT_SECRET=\"${{ secrets.GFYCAT_CLIENT_SECRET }}\"
          export DSCRD_CHNL_GENERAL=\"${{ secrets.DSCRD_CHNL_GENERAL }}\"
          "
          # Write the commands to a file
          echo "$commands" > environment.sh
      - name: Upload environment.sh as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: environment
          path: environment.sh
  
  check-env-file:
    name: check environment file
    runs-on: ubuntu-latest
    needs: setup-environment-file
    steps:
      - name: Download env.txt as an artifact
        uses: actions/download-artifact@v3
        with:
          name: environment
      - shell: bash
        run: |
          # Read the commands from the file
          source environment.sh
          # Print the environment variables
          echo $DSCRD_CHNL_GENERAL
  
  setup-env:
    #needs: call-format-and-lint
    runs-on: ubuntu-latest
    steps:
    - name: Set environment string
      run: |
        # Write the commands to set the environment variables to a string
        commands="# Set the environment variables
        export POLYGON_TOKEN=\"${{ secrets.POLYGON_TOKEN }}\"
        export TWITCH_BOT_USERNAME=\"${{ secrets.TWITCH_BOT_USERNAME }}\"
        export TWITCH_BOT_CLIENT_ID=\"${{ secrets.TWITCH_BOT_CLIENT_ID }}\"
        export TWITCH_BOT_CLIENT_SECRET=\"${{ secrets.TWITCH_BOT_CLIENT_SECRET }}\"
        export REDDIT_CLIENT_ID=\"${{ secrets.REDDIT_CLIENT_ID }}\"
        export REDDIT_CLIENT_SECRET=\"${{ secrets.REDDIT_CLIENT_SECRET }}\"
        export REDDIT_USERNAME=\"${{ secrets.REDDIT_USERNAME }}\"
        export REDDIT_PASSWORD=\"${{ secrets.REDDIT_PASSWORD }}\"
        export GFYCAT_CLIENT_ID=\"${{ secrets.GFYCAT_CLIENT_ID }}\"
        export GFYCAT_CLIENT_SECRET=\"${{ secrets.GFYCAT_CLIENT_SECRET }}\"
        export DSCRD_CHNL_GENERAL=\"${{ secrets.DSCRD_CHNL_GENERAL }}\"
        "
        echo "::set-env name=ENV_COMMANDS::$commands"
    - name: Call test python workflow
      uses: bpafoshizle/actions/.github/workflows/test-python.yml@add-test-python-workflow
      with:
        env-setup-command: ${{ env.ENV_COMMANDS }}

  call-test-python:
    # Ensure lint job passes before building image.
    needs: setup-env
    uses: bpafoshizle/actions/.github/workflows/test-python.yml@add-test-python-workflow
    with:
      env-setup-command: ${{ env.ENV_COMMANDS }}